### ISSUE TITLE
when publish the dateset?

### ISSUE THREAD

**Issue by wong1998** [Sentient07/HeadHunter#1]
I want to see the datasets,thank you!!

**Comment by Sentient07** [comment]
you can download the dataset from here : https://motchallenge.net/data/Head_Tracking_21/

**Comment by www516717402** [comment]
> you can download the dataset from here : https://motchallenge.net/data/Head_Tracking_21/

Great help. Thank you.

**Comment by Freezing-hxy** [comment]
The data set format is incorrect
