### ISSUE TITLE
how to set the anchor and choose the benchmark when running the tracker on a CroHD dataset(use_public" is false)

### ISSUE THREAD

**Issue by yx98314** [Sentient07/HeadHunter#12]
when I try to run the tracker on a CroHD dataset(training set) and **set the "use_public" option in the 'det_cfg' to 'False',**the ValueError said that "Anchors should be Tuple[Tuple[int]] because each feature map could potentially have different sizes and aspect ratios. "
 I noticed that in the obj_detect.py,if det_cfg['median_anchor']:the program can choose different benchmark to import different anchors,so which benchmark I should set in the det_cfg when I want to run the tracker on a CroHD dataset?And  I noticed that the benchmark should be associated with the anchor.py,too.
Another question is,if i set the "use_public" option in the 'det_cfg' to 'True',does it mean that I will use the data in det.txt which the dataset offers and the detector will not be used to detect the pedestrians or output anything.
![1635856049(1)](https://user-images.githubusercontent.com/67858482/139846102-be5834f3-4451-4bc5-bb8c-383d1e2ce54f.png)
![1635856090(1)](https://user-images.githubusercontent.com/67858482/139846218-5a923079-c2b6-46c7-a80b-51175e84a5ab.png)

**Comment by Sentient07** [comment]
Hello, sorry about the delayed response. Are you using the correct torchvision version? Please refer here : https://github.com/Sentient07/HeadHunter/issues/3#issuecomment-924951668

**Comment by yx98314** [comment]
It's kind of you to reply my question.I will try it tomorrow.And do you have the code when you fit the particlefilter into the JDE？I wonder how to deal with the particle regression problems considering Jde output the detection and embeddings together🥸---- Replied Message ----FromRamana ***@***.***>Date11/18/2021 23:45 ***@***.***> ***@***.******@***.***>SubjectRe: [Sentient07/HeadHunter] how to set the anchor and choose the benchmark when running the tracker on a CroHD dataset(use_public" is false) (Issue #12)
Hello, sorry about the delayed response. Are you using the correct torchvision version? Please refer here : #3 (comment)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Sentient07/HeadHunter/issues/12#issuecomment-972987101",
"url": "https://github.com/Sentient07/HeadHunter/issues/12#issuecomment-972987101",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sentient07** [comment]
Hello. i don't know what you refer to as "JDE" ?

**Comment by yx98314** [comment]
Hello.it's nice of you to reply the message. i am sorry that i misremembered.may be i was too sleepy last night.The question is:how can you replace the particle filter with a four state kf in headhunter-t. Do you have the code?And i also found that when i try to use only one gpu to train the Headhunter, the cuda is always out of memory(RTX 3070),is this the reason for distributed computing?---- Replied Message ----FromRamana ***@***.***>Date11/19/2021 17:14 ***@***.***> ***@***.******@***.***>SubjectRe: [Sentient07/HeadHunter] how to set the anchor and choose the benchmark when running the tracker on a CroHD dataset(use_public" is false) (Issue #12)
Hello. i don't know what you refer to as "JDE" ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Sentient07/HeadHunter/issues/12#issuecomment-973892087",
"url": "https://github.com/Sentient07/HeadHunter/issues/12#issuecomment-973892087",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sentient07** [comment]
>  the cuda is always out of memory(RTX 3070),is this the reason for distributed computing?

maybe. But did you also try to reduce batch size?
