### ISSUE TITLE
 raise ValueError("Anchors should be Tuple[Tuple[int]] because each feature "

### ISSUE THREAD

**Issue by haojie0616** [Sentient07/HeadHunter#13]
![2021-11-24 10-12-33 的屏幕截图](https://user-images.githubusercontent.com/23480460/143159105-639f1d53-accb-45af-8735-31170f7df015.png)
    anchors = self.grid_anchors(grid_sizes, strides)
  File "/home/haojie/下载/ENTER/envs/head_detection2/lib/python3.8/site-packages/torchvision/models/detection/anchor_utils.py", line 103, in grid_anchors
    raise ValueError("Anchors should be Tuple[Tuple[int]] because each feature "
ValueError: Anchors should be Tuple[Tuple[int]] because each feature map could potentially have different sizes and aspect ratios. There needs to be a match between the number of feature maps passed and the number of sizes / aspect ratios specified.
Killing subprocess 1055

**Comment by yx98314** [comment]
我之前也出现了这个问题，原因是anchor的数量跟anchor size不一样好像，你把anchor.py中的数量改成4个试试看

**Comment by Sentient07** [comment]
Hello. I'm sorry, I don't read Mandrian. Please feel free to open an issue in English if it's not resolved yet.
