### ISSUE TITLE
Can I use this model to train our own data set

### ISSUE THREAD

**Issue by neversettle-tech** [Sentient07/HeadHunter#15]
Two questions：
     1. Can I use this model to train our own data set？If so, what are the differences from the three data sets mentioned by the author.
     2. The groudTruth file is loaded in a different format than the readme file

**Comment by Sentient07** [comment]
Hello,

Thanks for your interest. Sorry, I am unaware of your dataset and it is out of scope of this repository to provide advise regarding custom/private dataset.
