### ISSUE TITLE
Hello, when I run the model, I get the following error

### ISSUE THREAD

**Issue by neversettle-tech** [Sentient07/HeadHunter#18]
ValueError: Anchors should be Tuple[Tuple[int]] because each feature map could potentially have different sizes and aspect ratios. There needs to be a match between the number of feature maps passed and the number of sizes / aspect ratios specified.

**Comment by stvogel** [comment]
I stumpled over the same error trying to train on the ScutHead-dataset.
Did you, @neversettle-tech had success solving this error? 
I adapted shead_anchors in anchors.py to only contain 4 anchors (instead of 8) ... at least than this error disappears only to get the next:
```
slice indices must be integers or None or have an __index__metod
File models/fast_rcnn.py line 457, in filter_proposals
  keep = keep[:self.post_nms_top_n
```
and indeed self.post_nms_top_n is a bound Method of CustomRPN ... I'm giving up :-(

**Comment by Sentient07** [comment]
I think this has to do with torchvision version. IIRC, it was 0.7.0. Since then, they've changed their part of their code. Perhaps I should've structured my code different. Let me know if that helps as I was able to run this code a few months ago.

**Comment by Sentient07** [comment]
@stvogel for instance see here : https://github.com/Sentient07/HeadHunter/issues/3#issuecomment-911029358

**Comment by stvogel** [comment]
Thanks for your help. I was confused about torch==1.8.1 in env_super.yml but should've read the closed issues.
torch==1.6.1 and torchvision==0.7.0 did the trick.

**Comment by Sentient07** [comment]
Great, glad could be of help. I released the code a year since the project took place. Hence, the environment file was different. If you have a working version of this codebase and corresponding environment file, feel free to send a PR. I'm closing this for now.

**Comment by MounirB** [comment]
> Thanks for your help. I was confused about torch==1.8.1 in env_super.yml but should've read the closed issues. torch==1.6.1 and torchvision==0.7.0 did the trick.

torch==1.6.1 doesn't seem to exist, did you mean 1.6.0 ?

**Comment by stvogel** [comment]
Sorry, yes ... torch==1.6.0 and as I learned now the versions for scipy and scikit-image are important as well.
Without replacing imread (to get the code working as is), I used scipy==1.1.0 and scikit-image==0.18.1
