### ISSUE TITLE
The env yml file?

### ISSUE THREAD

**Issue by D-Walter** [Sentient07/HeadHunter#2]
Hi Sentient07 
I have no idea about the actual env requirements of this project. Could you tell me more details?

**Comment by Sentient07** [comment]
Hi,

I've added the env file. Note that this contains additional package that's not entirely pertinent to this project. I didn't have time to remove them separately. However, this environment file works well for training/inference.

**Comment by Sentient07** [comment]
For those looking for an environment file, `env_super.yml` contains the required packages (and many more not pertinent to this project). If there is something with it, feel free to reopen this issue.
