### ISSUE TITLE
Questions about some results in the CVPR'21 paper

### ISSUE THREAD

**Issue by Johnqczhang** [Sentient07/HeadHunter#21]
Hi @Sentient07,

I'm confused about some results in your "[CVPR21 paper: Tracking Pedestrian Heads in Dense Crowd](https://openaccess.thecvf.com/content/CVPR2021/papers/Sundararaman_Tracking_Pedestrian_Heads_in_Dense_Crowd_CVPR_2021_paper.pdf)" cause some details are missing in the paper. Hope you can help me sort them out. Thanks!

1. The test set of SCUT-HEAD dataset consists of two parts: Part-A and Part-B. I find that other methods compared in Table 2 report respective results on both parts in their papers. So, which part did you use to run the evaluation to obtain the results in Table 2? Or is it the fact that the results in Table 2 are obtained by evaluating methods on the combination of both parts? Since I couldn't find the exact results of other compared methods in Table 2 in the corresponding cited papers, I'd like to know how did you obtain the results of these methods?

2. Table 4 shows the tracking results of your proposed tracker HeadHunter-T and other state-of-the-art trackers on the test set of CroHD. However, the results of HeadHunter-T in Table 4 are quite different from the results shown on the website of the [MOT benchmark](https://motchallenge.net/results/Head_Tracking_21/). Can you tell me what's the difference between these two results?

Looking forward to your reply. Thanks!

**Comment by Sentient07** [comment]
1) IIRC, it was both the parts. And for other methods, it's simply the average across both the parts. Note that our paper is not a head detection and it was _clearly_ stated that we used both the parts and is not necessary (compared to other papers) to be verbose in the text.

2) This is a known issue and has been reasoned out here : https://github.com/Sentient07/HeadHunter--T#note- . Please read the README before you ask questions
