### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by yzfly** [Sentient07/HeadHunter#3]
Can you share some pretrained weights?

**Comment by Sentient07** [comment]
Please refer [here](https://github.com/Sentient07/HeadHunter--T/issues/1). Note that you'd need to change the config file for reproducing the results on SCUT head. I don't seem to have that model on my system anymore. With the weights provided in the link, you will be able to reproduce results on our dataset.

**Comment by azizd15** [comment]
@Sentient07 Thanks for sharing the model. Can you tell me if the given model is trained for 4 anchors (1 anchor per fpn feature map) ?

**Comment by Sentient07** [comment]
Hi @azizd15 . Yes, I think so. It's been a year now, so I'm not 100% sure.

**Comment by azizd15** [comment]
Thank you for your answer, so the predefined anchors in the file anchors.py  do not work With the model that you shared because the model is designed with an anchor per fpn layer

**Comment by chinagaodali** [comment]
> Thank you for your answer, so the predefined anchors in the file anchors.py do not work With the model that you shared because the model is designed with an anchor per fpn layer

Hi, I met the same problem, have you figured it out?

**Comment by Sentient07** [comment]
Hello. 

Can you please elaborate on what you're trying to do? The commands you're using, the weights you're trying to load and the input?

**Comment by chinagaodali** [comment]
Thanks for you reply! 
I was try to run test.py with your pretrained weight as follow:
```
python test.py --context cpm
```
But there was something exception in model.forwad():
```
Traceback (most recent call last):
  File "/home/gdl/HeadHunter/test.py", line 173, in <module>
    test()
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/gdl/HeadHunter/test.py", line 162, in test
    outputs = model(images)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py", line 99, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torchvision/models/detection/rpn.py", line 332, in forward
    anchors = self.anchor_generator(images, features)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torchvision/models/detection/anchor_utils.py", line 149, in forward
    anchors_over_all_feature_maps = self.cached_grid_anchors(grid_sizes, strides)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torchvision/models/detection/anchor_utils.py", line 137, in cached_grid_anchors
    anchors = self.grid_anchors(grid_sizes, strides)
  File "/home/gdl/anaconda3/envs/env_super/lib/python3.8/site-packages/torchvision/models/detection/anchor_utils.py", line 103, in grid_anchors
    assert len(grid_sizes) == len(strides) == len(cell_anchors)
AssertionError
```
the value of len(grid_sizes) and len(strides) both are 4, but the value of len(cell_anchors) is 8

**Comment by Sentient07** [comment]
From your traceback, I think the error originates from torchvision and probably isn't related to the anchors at all. I can use the same anchors without any error. Perhaps can you try switching to `torchvision==0.7.0` ?

**Comment by jihai-cyber** [comment]
For the preprocessing .py program of the headhunter data set, you seem to have not uploaded it yet, can you please upload it? Thank you very much

**Comment by azizd15** [comment]
> > Thank you for your answer, so the predefined anchors in the file anchors.py do not work With the model that you shared because the model is designed with an anchor per fpn layer
> 
> Hi, I met the same problem, have you figured it out?

Hello @chinagaodali,

Sorry for late replay. I managed the problem by fixing the number of anchors to 5 (rather than 8) in the config file. For me it was the only solution that allows to use the pretrained model.

**Comment by Sentient07** [comment]
@azizd15 @chinagaodali I still can run it with `torchvision==0.7.0` and `pytorch==1.4.0` with the current settings. I don't think it'd be appropriate to change this.

**Comment by rmwor1d** [comment]
> > > Thank you for your answer, so the predefined anchors in the file anchors.py do not work With the model that you shared because the model is designed with an anchor per fpn layer
> > 
> > 
> > Hi, I met the same problem, have you figured it out?
> 
> Hello @chinagaodali,
> 
> Sorry for late replay. I managed the problem by fixing the number of anchors to 5 (rather than 8) in the config file. For me it was the only solution that allows to use the pretrained model.

Hello @azizd15 @chinagaodali, as @Sentient07 mentioned above, I changed the vision of **torchvision to 0.7.0** (with pytorch==1.6.0, albumentations==0.5.2), and cmd `python ./test.py --test_dataset ./dataset --plot_folder ./ --pretrained_model ./FT_R50_epoch_24.pth --context cpm` worked for me, where `./dataset` is the relative path to test images' folder.

**Comment by azizd15** [comment]
> 
> 
> > > > Thank you for your answer, so the predefined anchors in the file anchors.py do not work With the model that you shared because the model is designed with an anchor per fpn layer
> > > 
> > > 
> > > Hi, I met the same problem, have you figured it out?
> > 
> > 
> > Hello @chinagaodali,
> > Sorry for late replay. I managed the problem by fixing the number of anchors to 5 (rather than 8) in the config file. For me it was the only solution that allows to use the pretrained model.
> 
> Hello @azizd15 @chinagaodali, as @Sentient07 mentioned above, I changed the vision of **torchvision to 0.7.0** (with pytorch==1.6.0, albumentations==0.5.2), and cmd `python ./test.py --test_dataset ./dataset --plot_folder ./ --pretrained_model ./FT_R50_epoch_24.pth --context cpm` worked for me, where `./dataset` is the relative path to test images' folder.

Thank you @shmily326 for sharing your configuration. I tried it and it works. However, I am not sure that all the anchors are used by the model, because when I change the order of the anchors in the declaration I do not get the same detetions. I think that this version of torchvision take the first anchors that fits the size of the model (so only the first 5 anchors). MLore digging in that may be required to confirme it.
My best

**Comment by eplatero97** [comment]
Hello everyone, I have created a forked repository that includes the corresponding dependencies relative to torchvision 0.7.0 [here](https://github.com/eplatero97/HeadHunter). 

Given that this may not be a complete solution as @azizd15 points out, I look forward to hearing updates on the status of running headhunter on torchvision 0.7.0.

**Comment by Sentient07** [comment]
> because when I change the order of the anchors in the declaration I do not get the same detetions.

AFAIK, This is because different anchors are supposed to be applied at different resolution/stages and are not permutation invariant. i.e it doesn't make sense to use a smaller sized anchor at an early stage. 

That being said, I am not aware of how `torchvision` evolves and how they have changed the interface since `0.7.0`. This code was written for `torchvision==0.7.0` and in case anyone wishes to reproduce our results, I strongly advise to not change the configuration/order of anchors, rather use our code with the aforementioned version. Thank you
