### ISSUE TITLE
load state dict error

### ISSUE THREAD

**Issue by RichardoMrMu** [Sentient07/HeadHunter#5]
I run test.py. args.pretrained_model is from [this link](https://drive.google.com/file/d/1CODnsMrFrOCsE7XL9jBDP42GUz3rbUwH/view?usp=sharing). I meet this error:
RuntimeError: Error(s) in loading state_dict for FasterRCNN:
        Unexpected key(s) in state_dict: "backbone.ssh1.branch1.0.weight", "backbone.ssh1.branch1.1.weight", "backbone.ssh1.branch1.1.bias", "backbone.ssh1.branch1.1.running_mean", "backbone.ssh1.branch1.1.running_var", "backbone.ssh1.branch1.1.num_batches_tracked", "backbone.ssh1.branch2a.0.weight", "backbone.ssh1.branch2a.1.weight", "backbone.ssh1.branch2a.1.bias", "backbone.ssh1.branch2a.1.running_mean", "backbone.ssh1.branch2a.1.running_var", "backbone.ssh1.branch2a.1.num_batches_tracked", "backbone.ssh1.branch2b.0.weight", "backbone.ssh1.branch2b.1.weight", "backbone.ssh1.branch2b.1.bias", "backbone.ssh1.branch2b.1.running_mean", "backbone.ssh1.branch2b.1.running_var", "backbone.ssh1.branch2b.1.num_batches_tracked", "backbone.ssh1.branch2c.0.weight", "backbone.ssh1.branch2c.1.weight", "backbone.ssh1.branch2c.1.bias", "backbone.ssh1.branch2c.1.running_mean", "backbone.ssh1.branch2c.1.running_var", "backbone.ssh1.branch2c.1.num_batches_tracked", "backbone.ssh1.ssh_1.weight", "backbone.ssh1.ssh_1.bias", "backbone.ssh1.ssh_dimred.weight", "backbone.ssh1.ssh_dimred.bias", "backbone.ssh1.ssh_2.weight", "backbone.ssh1.ssh_2.bias", "backbone.ssh1.ssh_3a.weight", "backbone.ssh1.ssh_3a.bias", "backbone.ssh1.ssh_3b.weight", "backbone.ssh1.ssh_3b.bias", "backbone.ssh1.ssh_final.0.weight", "backbone.ssh1.ssh_final.1.weight", "backbone.ssh1.ssh_final.1.bias", "backbone.ssh1.ssh_final.1.running_mean", "backbone.ssh1.ssh_final.1.running_var", "backbone.ssh1.ssh_final.1.num_batches_tracked", "backbone.ssh2.branch1.0.weight", "backbone.ssh2.branch1.1.weight", "backbone.ssh2.branch1.1.bias", "backbone.ssh2.branch1.1.running_mean", "backbone.ssh2.branch1.1.running_var", "backbone.ssh2.branch1.1.num_batches_tracked", "backbone.ssh2.branch2a.0.weight", "backbone.ssh2.branch2a.1.weight", "backbone.ssh2.branch2a.1.bias", "backbone.ssh2.branch2a.1.running_mean", "backbone.ssh2.branch2a.1.running_var", "backbone.ssh2.branch2a.1.num_batches_tracked", "backbone.ssh2.branch2b.0.weight", "backbone.ssh2.branch2b.1.weight", "backbone.ssh2.branch2b.1.bias", "backbone.ssh2.branch2b.1.running_mean", "backbone.ssh2.branch2b.1.running_var", "backbone.ssh2.branch2b.1.num_batches_tracked", "backbone.ssh2.branch2c.0.weight", "backbone.ssh2.branch2c.1.weight", "backbone.ssh2.branch2c.1.bias", "backbone.ssh2.branch2c.1.running_mean", "backbone.ssh2.branch2c.1.running_var", "backbone.ssh2.branch2c.1.num_batches_tracked", "backbone.ssh2.ssh_1.weight", "backbone.ssh2.ssh_1.bias", "backbone.ssh2.ssh_dimred.weight", "backbone.ssh2.ssh_dimred.bias", "backbone.ssh2.ssh_2.weight", "backbone.ssh2.ssh_2.bias", "backbone.ssh2.ssh_3a.weight", "backbone.ssh2.ssh_3a.bias", "backbone.ssh2.ssh_3b.weight", "backbone.ssh2.ssh_3b.bias", "backbone.ssh2.ssh_final.0.weight", "backbone.ssh2.ssh_final.1.weight", "backbone.ssh2.ssh_final.1.bias", "backbone.ssh2.ssh_final.1.running_mean", "backbone.ssh2.ssh_final.1.running_var", "backbone.ssh2.ssh_final.1.num_batches_tracked", "backbone.ssh3.branch1.0.weight", "backbone.ssh3.branch1.1.weight", "backbone.ssh3.branch1.1.bias", "backbone.ssh3.branch1.1.running_mean", "backbone.ssh3.branch1.1.running_var", "backbone.ssh3.branch1.1.num_batches_tracked", "backbone.ssh3.branch2a.0.weight", "backbone.ssh3.branch2a.1.weight", "backbone.ssh3.branch2a.1.bias", "backbone.ssh3.branch2a.1.running_mean", "backbone.ssh3.branch2a.1.running_var", "backbone.ssh3.branch2a.1.num_batches_tracked", "backbone.ssh3.branch2b.0.weight", "backbone.ssh3.branch2b.1.weight", "backbone.ssh3.branch2b.1.bias", "backbone.ssh3.branch2b.1.running_mean", "backbone.ssh3.branch2b.1.running_var", "backbone.ssh3.branch2b.1.num_batches_tracked", "backbone.ssh3.branch2c.0.weight", "backbone.ssh3.branch2c.1.weight", "backbone.ssh3.branch2c.1.bias", "backbone.ssh3.branch2c.1.running_mean", "backbone.ssh3.branch2c.1.running_var", "backbone.ssh3.branch2c.1.num_batches_tracked", "backbone.ssh3.ssh_1.weight", "backbone.ssh3.ssh_1.bias", "backbone.ssh3.ssh_dimred.weight", "backbone.ssh3.ssh_dimred.bias", "backbone.ssh3.ssh_2.weight", "backbone.ssh3.ssh_2.bias", "backbone.ssh3.ssh_3a.weight", "backbone.ssh3.ssh_3a.bias", "backbone.ssh3.ssh_3b.weight", "backbone.ssh3.ssh_3b.bias", "backbone.ssh3.ssh_final.0.weight", "backbone.ssh3.ssh_final.1.weight", "backbone.ssh3.ssh_final.1.bias", "backbone.ssh3.ssh_final.1.running_mean", "backbone.ssh3.ssh_final.1.running_var", "backbone.ssh3.ssh_final.1.num_batches_tracked", "backbone.ssh4.branch1.0.weight", "backbone.ssh4.branch1.1.weight", "backbone.ssh4.branch1.1.bias", "backbone.ssh4.branch1.1.running_mean", "backbone.ssh4.branch1.1.running_var", "backbone.ssh4.branch1.1.num_batches_tracked", "backbone.ssh4.branch2a.0.weight", "backbone.ssh4.branch2a.1.weight", "backbone.ssh4.branch2a.1.bias", "backbone.ssh4.branch2a.1.running_mean", "backbone.ssh4.branch2a.1.running_var", "backbone.ssh4.branch2a.1.num_batches_tracked", "backbone.ssh4.branch2b.0.weight", "backbone.ssh4.branch2b.1.weight", "backbone.ssh4.branch2b.1.bias", "backbone.ssh4.branch2b.1.running_mean", "backbone.ssh4.branch2b.1.running_var", "backbone.ssh4.branch2b.1.num_batches_tracked", "backbone.ssh4.branch2c.0.weight", "backbone.ssh4.branch2c.1.weight", "backbone.ssh4.branch2c.1.bias", "backbone.ssh4.branch2c.1.running_mean", "backbone.ssh4.branch2c.1.running_var", "backbone.ssh4.branch2c.1.num_batches_tracked", "backbone.ssh4.ssh_1.weight", "backbone.ssh4.ssh_1.bias", "backbone.ssh4.ssh_dimred.weight", "backbone.ssh4.ssh_dimred.bias", "backbone.ssh4.ssh_2.weight", "backbone.ssh4.ssh_2.bias", "backbone.ssh4.ssh_3a.weight", "backbone.ssh4.ssh_3a.bias", "backbone.ssh4.ssh_3b.weight", "backbone.ssh4.ssh_3b.bias", "backbone.ssh4.ssh_final.0.weight", "backbone.ssh4.ssh_final.1.weight", "backbone.ssh4.ssh_final.1.bias", "backbone.ssh4.ssh_final.1.running_mean", "backbone.ssh4.ssh_final.1.running_var", "backbone.ssh4.ssh_final.1.num_batches_tracked".
what should i do?

**Comment by Sentient07** [comment]
Hello,

As mentioned in that thread, those weights are for reproducing the results on our benchmark alone. That being said, it's hard to say more without knowing the commands you had used. Did you pass `--context cpm` ?

**Comment by RichardoMrMu** [comment]
I use the default parameters in test.py. 
parser = argparse.ArgumentParser(description='Testing script')
parser.add_argument('--test_dataset', help='Dataset .txt file')
parser.add_argument('--pretrained_model', default="./weight/FT_R50_epoch_24.pth",help='resume net for retraining')
parser.add_argument('--plot_folder', default="./imagedata",help='Location to plot results on images')

parser.add_argument('--world_size', default=1, type=int, help='number of distributed processes')

parser.add_argument('--benchmark', default='ScutHead', help='Benchmark for training/validation')
parser.add_argument('--batch_size', default=1, type=int, help='Batch size')
parser.add_argument('--min_size', default=800, type=int, help='Optionally plot first N images of test')
parser.add_argument('--max_size', default=1400, type=int, help='Optionally plot first N images of test')

parser.add_argument('--ext', default='.jpg', type=str, help='Image file extensions')
parser.add_argument('--outfile', help='Location to save results in mot format')

parser.add_argument('--backbone', default='resnet50', help='Backbone network mobile0.25 or resnet50')
parser.add_argument('--context', help='Whether to use context model')
parser.add_argument('--use_deform', default=False, type=bool, help='Use Deformable SSH')
parser.add_argument('--det_thresh', default=0.3, type=float, help='Number of workers used in dataloading')
parser.add_argument('--default_filter', default=False, type=bool, help='Use old filters')
parser.add_argument('--soft_nms', default=False, type=bool, help='Use soft nms?')
parser.add_argument('--upscale_rpn', default=False, type=bool, help='Upscale RPN feature maps')

**Comment by Sentient07** [comment]
Hello. By passing the correct `--plot_folder` and `--context` parameter, I'm able to restore and train/evaluate. Please try them and if there is something else, feel free to reopen this issue. Closing as I think I've answered.
