### ISSUE TITLE
About GPU memory requirement.

### ISSUE THREAD

**Issue by NonameZ-HTY** [Sentient07/HeadHunter#6]
How much GPU memory is recommanded when training the model using ScutHead dataset? I've found a memory insufficience error when trying to train the model on a idel GPU with 4041MB memory and batch size 1.
Besides, there is some minor bugs in the "head_detection/data/create_scuthead.py" file, as _args.dset_path_ is defined but _args.dset_dir_ is used (and the same bugs to the _arg.save_path_ and _args.out_path_).

**Comment by Sentient07** [comment]
Hello, 

I'm not sure about the exact memory requirement. You can disable the transpose convolution to save a significant amount of memory. Note that this might lead to slightly inferior performances. Other than that, you can also reduce the input size (resolution). Again this can hurt the accuracy. I ran my code on 2080Ti, with ~11Gb of memory. 

Thanks for pointing out the bug. Honestly, the python file is a copy paste from my notebook, so I could've made some mistakes there. Will be much happy to take a PR :-)

**Comment by NonameZ-HTY** [comment]
Thank you for your reply.
