### ISSUE TITLE
how to solve fast_rcnn.py

### ISSUE THREAD

**Issue by Freezing-hxy** [Sentient07/HeadHunter#7]
File "/home/project/HeadHunter-master/head_detection/models/fast_rcnn.py", line 496, in forward
    boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
  File "/home/project/HeadHunter-master/head_detection/models/fast_rcnn.py", line 458, in filter_proposals
    keep = keep[:self.post_nms_top_n]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by Sentient07** [comment]
Can you please elaborate on what you're trying? Arguments you're using?

**Comment by Sentient07** [comment]
Closing as there is no response. Please feel free to reopen if anyone else faces this issue

**Comment by hawkingeric** [comment]
Hi,
I also face this issue .

 File "/home/ericpan/Project/HeadHunter/head_detection/models/fast_rcnn.py", line 515, in forward
    boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
  File "/home/ericpan/Project/HeadHunter/head_detection/models/fast_rcnn.py", line 461, in filter_proposals
    keep = keep[:self.post_nms_top_n]


The auguments I use is shown below.
CUDA_VISIBLE_DEVICES=0 python train.py --cfg_file config/SHead/ScutHead_R50.yaml --world_size 1 --num_workers 4

**Comment by Sentient07** [comment]
@hawkingeric sorry I don't see an error message in your comment? Also, what is your version of torchvision ?

**Comment by hawkingeric** [comment]
Hi, thank you for your reply.
I solved this issue by changing the torchvision version from 0.9.1 to 0.7.0 .
Also, my torch version is 1.6.0 .
