### ISSUE TITLE
The data set format is incorrect

### ISSUE THREAD

**Issue by Freezing-hxy** [Sentient07/HeadHunter#8]
The data set format is incorrect

**Comment by Sentient07** [comment]
What do you mean by incorrect? It follows what has been outlined in the paper. Furthermore, the baselines have been verified by an automated and well accepted evaluation scheme here : https://motchallenge.net/results/Head_Tracking_21/. Please try to be more precise.

**Comment by Freezing-hxy** [comment]
create_chuman.py cannot be used to process data

**Comment by Freezing-hxy** [comment]
> What do you mean by incorrect? It follows what has been outlined in the paper. Furthermore, the baselines have been verified by an automated and well accepted evaluation scheme here : https://motchallenge.net/results/Head_Tracking_21/. Please try to be more precise.

create_chuman.py cannot be used to process data

**Comment by Sentient07** [comment]
As it says in that file, it's for processing crowdhuman and not our dataset
